import json
import os
import pathlib
import argparse
import sys

# Default Provider Settings
PROVIDERS = {
    "gmail": {
        "imap": {"host": "imap.gmail.com", "port": 993, "tls": True},
        "smtp": {"host": "smtp.gmail.com", "port": 587, "tls": True, "tls_starttls": "on"}
    },
    "outlook": {
        "imap": {"host": "outlook.office365.com", "port": 993, "tls": True},
        "smtp": {"host": "smtp.office365.com", "port": 587, "tls": True, "tls_starttls": "on"}
    },
    "fastmail": {
        "imap": {"host": "imap.fastmail.com", "port": 993, "tls": True},
        "smtp": {"host": "smtp.fastmail.com", "port": 465, "tls": True, "tls_starttls": "off"}
    }
}

def load_config():
    config_dir = os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))
    base_path = pathlib.Path(config_dir) / "cairn-mail"
    
    accounts_path = base_path / "accounts.json"
    settings_path = base_path / "config.json"
    
    if not accounts_path.exists():
        print(f"Error: Configuration not found at {accounts_path}")
        sys.exit(1)
        
    with open(accounts_path, 'r') as f:
        accounts = json.load(f)
        
    settings = {}
    if settings_path.exists():
        with open(settings_path, 'r') as f:
            settings = json.load(f)
            
    return accounts, settings

def get_account_defaults(flavor):
    return PROVIDERS.get(flavor, {})

def generate_mbsync(accounts, settings, oauth_script=None):
    maildir_base = settings.get("settings", {}).get("maildirBase", "~/Mail")
    # Ensure expansion ~ -> /home/user
    abs_base = os.path.expanduser(maildir_base)
    
    lines = [f"# Generated by cairn-mail\n"]
    
    for name, acc in accounts.items():
        # Ensure account directory exists
        acc_path = os.path.join(abs_base, name)
        os.makedirs(acc_path, exist_ok=True)
        
        flavor = acc.get("flavor", "manual")
        defaults = get_account_defaults(flavor).get("imap", {})
        
        host = acc["imap"]["host"] or defaults.get("host")
        port = acc["imap"]["port"] or defaults.get("port")
        user = acc["userName"] or acc["address"]
        pass_cmd = acc["passwordCommand"]
        
        # Auto-configuration for OAuth2 providers
        if flavor in ["gmail", "outlook"]:
            # Logic: If pass_cmd looks like a file path, wrap it with mutt_oauth2.py
            # basic check: starts with / or ~, or ends with .gpg/.json
            if pass_cmd and (pass_cmd.startswith("/") or pass_cmd.startswith("~") or pass_cmd.endswith(".gpg")):
                if oauth_script:
                    pass_cmd = f"python3 {oauth_script} {pass_cmd}"

        lines.append(f"IMAPAccount {name}")
        lines.append(f"Host {host}")
        lines.append(f"Port {port}")
        lines.append(f"User {user}")
        lines.append(f"PassCmd \"{pass_cmd}\"")
        lines.append(f"SSLType IMAPS")
        lines.append(f"PassCmd \"{pass_cmd}\"")
        lines.append(f"SSLType IMAPS")
        
        auth_mech = "LOGIN"
        if flavor in ["gmail", "outlook"] and "oauth" in pass_cmd:
             auth_mech = "XOAUTH2"
        
        lines.append(f"AuthMechs {auth_mech}")
        lines.append("")
        
        lines.append(f"IMAPStore {name}-remote")
        lines.append(f"Account {name}")
        lines.append("")
        
        lines.append(f"MaildirStore {name}-local")
        lines.append(f"Path {maildir_base}/{name}/")
        lines.append(f"Inbox {maildir_base}/{name}/Inbox")
        lines.append(f"SubFolders Verbatim")
        lines.append("")
        
        lines.append(f"Channel {name}")
        lines.append(f"Far :{name}-remote:")
        lines.append(f"Near :{name}-local:")
        lines.append(f"Patterns *")
        lines.append(f"Create Both")
        lines.append(f"Expunge Both")
        lines.append(f"SyncState *")
        lines.append("")
        
    return "\n".join(lines)

def generate_msmtp(accounts, oauth_script=None):
    lines = ["# Generated by cairn-mail", "defaults", "auth on", "tls on", "tls_trust_file /etc/ssl/certs/ca-certificates.crt", "logfile ~/.msmtp.log", ""]
    
    for name, acc in accounts.items():
        flavor = acc.get("flavor", "manual")
        defaults = get_account_defaults(flavor).get("smtp", {})
        
        host = acc["smtp"]["host"] or defaults.get("host")
        port = acc["smtp"]["port"] or defaults.get("port")
        starttls = defaults.get("tls_starttls", "on")
        user = acc["userName"] or acc["address"]
        pass_cmd = acc["passwordCommand"]
        auth_mech = "on" # Default for password auth
        
        # Auto-configuration for OAuth2 providers
        if flavor in ["gmail", "outlook"]:
            if pass_cmd and (pass_cmd.startswith("/") or pass_cmd.startswith("~") or pass_cmd.endswith(".gpg")):
                if oauth_script:
                    pass_cmd = f"python3 {oauth_script} {pass_cmd}"
                auth_mech = "oauthbearer" if flavor == "gmail" else "xoauth2"
        
        lines.append(f"account {name}")
        lines.append(f"host {host}")
        lines.append(f"port {port}")
        lines.append(f"from {acc['address']}")
        lines.append(f"user {user}")
        lines.append(f"passwordeval \"{pass_cmd}\"")
        lines.append(f"tls_starttls {starttls}")
        lines.append(f"auth {auth_mech}")
        lines.append("")
        
        if acc.get("primary", False):
             lines.append(f"account default : {name}")
    
    return "\n".join(lines)

def generate_notmuch(accounts, settings):
    maildir_base = settings.get("settings", {}).get("maildirBase", "~/Mail")
    primary_email = ""
    user_name = "User"
    other_emails = []
    
    for name, acc in accounts.items():
        if acc.get("primary", False):
            primary_email = acc["address"]
            user_name = acc.get("realName", "User")
        else:
            other_emails.append(acc["address"])
            
    if not primary_email and other_emails:
        primary_email = other_emails.pop(0)

    lines = []
    lines.append("[database]")
    lines.append(f"path={os.path.expanduser(maildir_base)}")
    lines.append("")
    
    lines.append("[user]")
    lines.append(f"name={user_name}")
    lines.append(f"primary_email={primary_email}")
    if other_emails:
        lines.append(f"other_email={';'.join(other_emails)}")
    lines.append("")
    
    lines.append("[new]")
    lines.append("tags=new")
    lines.append("ignore=")
    lines.append("")
    
    lines.append("[search]")
    lines.append("exclude_tags=deleted;spam;")
    lines.append("")
    
    lines.append("[maildir]")
    lines.append("synchronize_flags=true")
    
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--oauth-script", help="Path to mutt_oauth2.py script", default=None)
    args = parser.parse_args()

    oauth_script = args.oauth_script
    # Fallback to sibling file if not provided (for non-Nix usage)
    if not oauth_script:
        sibling = pathlib.Path(__file__).parent / "mutt_oauth2.py"
        if sibling.exists():
            oauth_script = str(sibling.resolve())

    try:
        accounts, settings = load_config()
        
        mbsync_conf = generate_mbsync(accounts, settings, oauth_script)
        msmtp_conf = generate_msmtp(accounts, oauth_script)
        notmuch_conf = generate_notmuch(accounts, settings)
        
        home = pathlib.Path.home()
        
        with open(home / ".mbsyncrc", "w") as f:
            f.write(mbsync_conf)
        print("Generated ~/.mbsyncrc")
        
        with open(home / ".msmtprc", "w") as f:
            f.write(msmtp_conf)
        print("Generated ~/.msmtprc")
        
        # Write Notmuch config to standard XDG location (Notmuch 0.32+)
        config_home = os.environ.get("XDG_CONFIG_HOME", os.path.join(str(home), ".config"))
        notmuch_config_path = pathlib.Path(config_home) / "notmuch" / "default" / "config"
        notmuch_config_path.parent.mkdir(parents=True, exist_ok=True)

        with open(notmuch_config_path, "w") as f:
            f.write(notmuch_conf)
        print(f"Generated {notmuch_config_path}")
        
    except Exception as e:
        print(f"Failed to generate configs: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
